ignored_packages:
  - mini_racer
  - rmagick # https://github.com/rmagick/rmagick/issues/256
package_aliases:
  concurrent-ruby: ruby-concurrent  # 'concurrent-ruby' should be mapped to 'ruby-concurrent-ruby' package name but instead it named as 'ruby-concurrent'
